[package]
name = "promscale_rs"
version = "0.3.2"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true

[features]
default = []
pg12 = ["pgx/pg12", "pgx-tests/pg12"]
pg13 = ["pgx/pg13", "pgx-tests/pg13"]
pg14 = ["pgx/pg14", "pgx-tests/pg14"]

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
pgx = "0.4.3"
pgx-macros = "0.4.3"

[dev-dependencies]
pgx-tests = "0.4.3"
