[package]
name = "sql-tests"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
insta = "1.14.0"
test-generator = "0.3.0"
test-common = { path = "../test-common" }
pgtap-parse = { path = "../pgtap-parse" }

[build-dependencies]
build-deps = "^0.1"
