-- The contents of this file was auto-generated by the pgx extension, but was
-- placed here manually

-- src/backend_telemetry_buffer.rs:182
-- promscale::backend_telemetry_buffer::_prom_ext::pop_recs
-- requires:
--   backend_telemetry_rec_decl
CREATE OR REPLACE FUNCTION _prom_ext."pop_recs"() RETURNS SETOF _prom_ext.backend_telemetry_rec /* pgx::heap_tuple::PgHeapTuple<pgx::pgbox::AllocatedByRust> */
STRICT VOLATILE 
LANGUAGE c /* Rust */
AS '$libdir/promscale-{{extension_version}}', 'pop_recs_wrapper';

-- src/backend_telemetry_buffer.rs:172
-- promscale::backend_telemetry_buffer::_prom_ext::push_rec
-- requires:
--   backend_telemetry_rec_decl
CREATE OR REPLACE FUNCTION _prom_ext."push_rec"(
	"r" _prom_ext.backend_telemetry_rec /* pgx::heap_tuple::PgHeapTuple<pgx::pgbox::AllocatedByRust> */
) RETURNS bool /* bool */
STRICT VOLATILE 
LANGUAGE c /* Rust */
AS '$libdir/promscale-{{extension_version}}', 'push_rec_wrapper';